-- NOTE: this file used to carry four UIDropDownMenu taint workarounds
-- (COMMUNITY_UIDD_REFRESH / UIDROPDOWNMENU_OPEN / UIDROPDOWNMENU_VALUE /
-- UIDD_REFRESH_OVERREAD). Blizzard replaced the UIDropDownMenu system wholesale
-- in 11.0 -- no Blizzard menu routes through it any more -- and removed
-- Communities_LoadUI, so hooksecurefunc("Communities_LoadUI", ...) raised at load
-- and took the entire addon down with it. The bugs those blocks patched no longer
-- exist; menu entries now go through Menu.ModifyMenu (see ui/ui.lua).



local bracketsColors = { 
	["gladiator"] = "|cfff1c40f",
	["hero"] = "|cfff1c40f",
	["elite"] = "|cffa335ee",
	["duelist"] = "|cff0070dd",
	["rival"] = "|cff27ae60",
	["challenger"] = "|cffffffff",
	["combatant"] = "|cff9d9d9d",
	["none"] = "|cffffffff"
}

local ranksColors = {
	[2700] = "|cffff8000",
	[2400] = "|cffa335ee",
	[2100] = "|cff0070dd",
	[1750] = "|cff27ae60",
	[1749] = "|cffffffff",
}

-- AMPVP_AchievementsAndTitlesList is generated by the backend into
-- regionalData/titles.lua (loaded before this file), so a new season's titles need
-- no addon edit. The old hard-coded table stopped at Shadowlands season 4, which
-- is why every Dragonflight / War Within / Midnight title rendered blank.
-- AMPVP_SPECLIST (specialization id => "Spec Class") comes from regionalData/specs.lua.
-- Both are declared here only as a safety net if those files fail to load.
AMPVP_AchievementsAndTitlesList = AMPVP_AchievementsAndTitlesList or {}
AMPVP_SPECLIST = AMPVP_SPECLIST or {}

function AMPVP_ConvertStringToTable(str, character)
  local result = {}
  local index = 1
  
  for s in string.gmatch(str, "[^"..character.."]+") do
    result[index] = s
    index = index + 1
  end

  return result
end

function AMPVP_ConvertRankAchievement(rankName)
	if rankName == nil then
		return ""
	end
	local newTitleName = "";
	
	for rankIndex, name in pairs(AMPVP_AchievementsAndTitlesList) do
	
		if name == rankName then
			for bracketName, bracketColor in pairs(bracketsColors) do
				if string.find(string.lower(rankName), bracketName) then
					newTitleName = bracketsColors[bracketName] .. rankName .. "|r"
				end
			end
		end
	
	end
	
	if newTitleName == "" then
	
		local tempTable = AMPVP_ConvertStringToTable(rankName, " ")
		local rankPoints = nil
		
		for k, v in pairs(tempTable) do
			if tonumber(tempTable[k]) ~= nil then
				rankPoints = tonumber(v)
			end
		end
		
		if rankPoints ~= nil then

			if rankPoints >= 2700 then
				newTitleName = ranksColors[2700]..rankName.."|r"
			elseif rankPoints >= 2400 then
				newTitleName = ranksColors[2400]..rankName.."|r"
			elseif rankPoints >= 2100 then
				newTitleName = ranksColors[2100]..rankName.."|r"
			elseif rankPoints >= 1750 then
				newTitleName = ranksColors[1750]..rankName.."|r"
			elseif rankPoints < 1750 then
				newTitleName = ranksColors[1749]..rankName.."|r"
			end

		end
		
		if newTitleName == "" then
			newTitleName = bracketsColors["none"] .. rankName .. "|r"
		end
	end
	
	return newTitleName
	
end

function AMPVP_ConvertDateToStandardEU(datet)

	if datet == nil then return "No date available" end
	
	local tableMonths = {
		[1] = "January",
		[2] = "February",
		[3] = "March",
		[4] = "April",
		[5] = "May",
		[6] = "June",
		[7] = "July",
		[8] = "August",
		[9] = "September",
		[10] = "October",
		[11] = "November",
		[12] = "December",
	}
	
	local day, month, year = string.split("/", datet)
	
	if day and month and year then
		month = tableMonths[tonumber(month)]
		year = "20"..year
	end
	
	local tempDate = day .." ".. month .." ".. year
	return tempDate
	
end



local backdrop = {
	bgFile = "Interface\\DialogFrame\\UI-DialogBox-Background",
	edgeFile =  "Interface\\DialogFrame\\UI-DialogBox-Border",
	tile = true, tileSize = 0, edgeSize = 15,
	insets = { left = 5, right = 5, top = 5, bottom = 5 },
}

local backdrop2 = {
	bgFile = "Interface/Tooltips/UI-Tooltip-Background-Corrupted",
	edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border",
	tile = true, tileSize = 16, edgeSize = 16,
	insets = { left = 4, right = 4, top = 4, bottom = 4 },
}
function AMPVP_CreateTableFromString(inputStr, sep)

	local separator = sep

	if separator == nil then
		separator = "%s"
	end

	local tempTab = {}

	for str in string.gmatch(inputStr, "([^"..separator.."]+)") do

		table.insert(tempTab, str)

	end

	return tempTab

end

function AMPVP_IsTaintable()
    return (InCombatLockdown() or (UnitAffectingCombat("player") or UnitAffectingCombat("pet")))
end

function AMPVP_CreateFrame(frameName, frameParent, lrOffset, xOffset, yOffset, sizeX, sizeY, alphaBG, movable)

	local frame = CreateFrame("frame", frameName, frameParent, "SecureHandlerStateTemplate" and BackdropTemplateMixin and "BackdropTemplate")
	frame:SetPoint(lrOffset, frameParent, xOffset, yOffset)
	frame:SetSize(sizeX, sizeY)
	frame.t = frame:CreateTexture()
	frame.t:SetColorTexture(0, 0, 0, alphaBG or 1)
	frame.t:SetSize(sizeX - 5, sizeY - 5)
	frame.t:SetPoint("CENTER", frame, 0, 0)
	--frame.t:SetAllPoints(frame)
	frame:SetBackdrop(backdrop)
	if movable then
		frame:EnableMouse(true)
		frame:RegisterForDrag("LeftButton")
		frame:SetMovable(true)
		frame:SetUserPlaced(true)
		frame:SetScript("OnDragStart", frame.StartMoving)
		frame:SetScript("OnDragStop", frame.StopMovingOrSizing)
	end

end

function AMPVP_CreateFrame2(frameName, frameParent, lrOffset, xOffset, yOffset, sizeX, sizeY, alphaBG, movable)

	local frame = CreateFrame("frame", frameName, frameParent, "SecureHandlerStateTemplate" and BackdropTemplateMixin and "BackdropTemplate")
	frame:SetPoint(lrOffset, frameParent, xOffset, yOffset)
	frame:SetSize(sizeX, sizeY)
	--frame.t:SetAllPoints(frame)
	frame:SetBackdrop(backdrop2)
	if movable then
		frame:EnableMouse(true)
		frame:RegisterForDrag("LeftButton")
		frame:SetMovable(true)
		frame:SetUserPlaced(true)
		frame:SetScript("OnDragStart", frame.StartMoving)
		frame:SetScript("OnDragStop", frame.StopMovingOrSizing)
	end

end

function AMPVP_AddDoubleLine(frameText1, frameText2, line1, line2)

	if frameText1 ~= nil then
		frameText1:SetText(line1)
	end

	if frameText2 ~= nil then
		frameText2:SetText(line2)
	end

end

function AMPVP_CreateText(frameName, frameParent, lrOffset, xOffset, yOffset, text, fontName)

	if frameParent ~= nil then
		local frameText = frameParent:CreateFontString(frameName, "ARTWORK", fontName or "GameFontNormal")
		frameText:SetPoint(lrOffset, frameParent, xOffset, yOffset)
		frameText:SetText(text)
	end

end

function AMPVP_CreateText2(frameName, frameParent, lrOffset, xOffset, yOffset, text, fontName)

	if frameParent ~= nil then
		local frameText = frameParent:CreateFontString(frameName, "ARTWORK", fontName or "GameFontNormal")
		frameText:SetPoint(lrOffset, frameParent, xOffset, yOffset)
		frameText:SetText(text)
	end

end

function AMPVP_FormatValue(value)
    if value >= 1e6 then
        return tonumber(format("%.1f", value/1e6)).."m"
    elseif value >= 1e3 then
        return tonumber(format("%.1f", value/1e3)).."k"
    else
        return value
    end
end

function AMPVP_CreateButton(buttonName, frameParent, lrOffset, xOffset, yOffset, sizeX, sizeY, text)

	local button = CreateFrame("Button", "$parent"..buttonName, frameParent, "UIPanelButtonTemplate")
	button:SetSize(sizeX,sizeY)
	button:SetPoint(lrOffset, frameParent, xOffset, yOffset)
	local textLength = string.len(text)
	if textLength > 35 then
		button:SetText(text:sub(1, 35).."...")
	else
		button:SetText(text)
	end

end

function AMPVP_CreateCloseButton(frameParent)

	local closeButton = CreateFrame("Button", nil, frameParent, "UIPanelCloseButton")
	closeButton:SetPoint("TOPRIGHT", -5, -5)
	closeButton:SetHitRectInsets(5, 5, 5, 5)

end

function AMPVP_CreateCheckbox(boxName, frameParent, lrOffset, xOffset, yOffset, text)


	local checkbox = CreateFrame("CheckButton", "$parent"..boxName, frameParent, "UICheckButtonTemplate")
	checkbox:ClearAllPoints()
	checkbox:SetPoint(lrOffset, frameParent, xOffset, yOffset)
	_G[checkbox:GetName() .. "Text"]:SetText(text)

end

function AMPVP_CreateEditBox(boxName, frameParent, lrOffset, xOffset, yOffset, sizeX, sizeY, text)

	local editboxframe = frameParent:CreateFontString(boxName, "ARTWORK", "GameFontHighlightSmall")
	editboxframe:SetPoint(lrOffset, xOffset, yOffset)
	editboxframe:SetText(text)

	editboxframe.titleinputframe = CreateFrame("Frame", "$parentInputFrame", frameParent, "SecureHandlerStateTemplate" and BackdropTemplateMixin and "BackdropTemplate")
	editboxframe.titleinputframe:SetWidth(sizeX)
	editboxframe.titleinputframe:SetHeight(sizeY)
	editboxframe.titleinputframe:SetBackdrop(backdrop)
	editboxframe.titleinputframe:SetPoint("TOPLEFT", editboxframe, "BOTTOMLEFT", 40, 15)
	editboxframe.titleinputbox = CreateFrame("EditBox", "$parentTitleText", editboxframe.titleinputframe)
	editboxframe.titleinputbox:SetWidth(sizeX)
	editboxframe.titleinputbox:SetHeight(24)
	editboxframe.titleinputbox:SetMaxLetters(100)
	editboxframe.titleinputbox:SetNumeric(false)
	editboxframe.titleinputbox:SetAutoFocus(false)
	editboxframe.titleinputbox:SetFontObject("GameFontHighlightSmall")
	editboxframe.titleinputbox:SetPoint("TOPLEFT", 5, 1)
	--editboxframe.titleinputbox:SetScript("OnShow", editboxframe.titleinputbox.SetFocus)
	editboxframe.titleinputbox:SetScript("OnEscapePressed", editboxframe.titleinputbox.ClearFocus)
	editboxframe.titleinputbox:SetScript("OnEnterPressed", editboxframe.titleinputbox.ClearFocus)


end

function AMPVP_CreateText(frameName, frameParent, lrOffset, xOffset, yOffset, text)

	if frameParent ~= nil then
		local frameText = frameParent:CreateFontString(frameName, "ARTWORK", "GameFontNormal")
		frameText:SetPoint(lrOffset, frameParent, xOffset, yOffset)
		frameText:SetText(text)
	end

end

function AMPVP_CreateButtonText(txt, btnName, frameParent, region, posX, posY, font, textureWithPath, fontColor, sizeX, sizeY, isBlack)

	local btnName = CreateFrame("Button", "$parent"..btnName, frameParent)
	btnName:ClearAllPoints()
	if btnName.ClearNormalTexture then
		btnName:ClearNormalTexture()
	end
	if sizeX == nil then
		btnName:SetSize(120, 35)
	else
		btnName:SetSize(sizeX, sizeY)
	end
	btnName:SetPoint(region,posX,posY)
	btnName.text = btnName:CreateFontString("$parentText", "OVERLAY", font)
	--btnName.text:SetAllPoints(btnName)
	btnName.text:SetText(txt)

	if fontColor ~= nil then
		btnName.text:SetTextColor(unpack(fontColor))
	end

	if isBlack ~= nil then

		btnName.t = btnName:CreateTexture(nil, "BACKGROUND")
		btnName.t:SetSize(30, 27)
		btnName.t:SetColorTexture(0, 0, 0, 0.3)
		btnName.t:SetPoint("CENTER", btnName, 0, 0)

	end

	if textureWithPath ~= nil then
		btnName.icon = btnName:CreateTexture("$parentTexture", 'OVERLAY')
		btnName.icon:SetTexture(textureWithPath)
		btnName.icon:SetSize(15, 15)
		btnName.icon:SetPoint('LEFT')
	end

	if textureWithPath ~= nil then
		btnName.text:SetPoint('LEFT', btnName.icon, 'RIGHT', 5, 0)
	else
		btnName.text:SetPoint('CENTER', btnName, 0, 0)
	end

end


function AMPVP_Print(msg, clr)

	local defClr = "|cffffffff"

	if clr == "green" then
		defClr = "|cff66ff33"
	elseif clr == "red" then
		defClr = "|cffff0000"
	elseif clr == "blue" then
		defClr = "|cff0033cc"
	end

	print("[ArenaMaster.IO]: "..defClr..msg.."|r")

end

function AMPVP_ColorSub(thing, color, isPercentage)

	if not isPercentage then
		if color == "white" then
			thing = "|cffffffff"..thing.."|r";
		elseif color == "redwinrate" then
			thing = "|cffc43244"..thing.."|r";
		elseif color == "green" then
			thing = "|cff66ff33"..thing.."|r";
		elseif color == "greenwinrate" then
			thing = "|cff53ca41"..thing.."|r";
		end
	else
		if color == "white" then
			thing = "|cffffffff"..thing.."%".."|r";
		elseif color == "redwinrate" then
			thing = "|cffc43244"..thing.."%".."|r";
		elseif color == "greenwinrate" then
			thing = "|cff53ca41"..thing.."%".."|r";
		end
	end
	return thing;

end

function AMPVP_RatingColorManager(points)

	local finalPoints = ""

	if points >= 2700 then
		finalPoints = ranksColors[2700]..points.."|r"
	elseif points >= 2400 then
		finalPoints = ranksColors[2400]..points.."|r"
	elseif points >= 2100 then
		finalPoints = ranksColors[2100]..points.."|r"
	elseif points >= 1750 then
		finalPoints = ranksColors[1750]..points.."|r"
	elseif points < 1750 then
		finalPoints = ranksColors[1749]..points.."|r"
	end

	return finalPoints

end

function AMPVP_FixSlangRealms(realmName)

	local result = "";

	realmName = string.gsub(realmName, " ", "")

	for name, slug in pairs(AMPVP_REALMLIST) do

		name = string.gsub(name, " ", "")

		if name == realmName then
			result = slug
		end

	end

	if result == "" then

		result = realmName -- for cases like russian realms. not yet fixed черныйшрам - 's slug is not available;

	end

	return result

end


function AMPVP_LoginSettingsLoadSave()

	if AMPVP_SettingsVar == nil then
		AMPVP_SettingsVar = {
			addonInitialized = false,
		--main settings
			--Current Rating
			CURR_RATING_2s = true,
			CURR_RATING_3s = true,
			CURR_RATING_RBG = true,
			--Current Season Stats
			CURR_SEASON_2SW = true,
			CURR_SEASON_3SW = true,
			CURR_SEASON_RBGW = true,
			CURR_SEASON_TITLES = true,
			--Character Experience
			CHAR_EXP_2s = true,
			CHAR_EXP_3s = true,
			CHAR_EXP_RBG = true,
			--Highest Account Rating
			HIGHEST_ACC_2s = true,
			HIGHEST_ACC_3s = true,
			HIGHEST_ACC_RBG = true,
			--Character Stats
			STATS_ITEMLEVEL = true,
			STATS_VERSATILITY = true,
			STATS_COVENANT = true,
			STATS_RENOWN = true,
			STATS_HEALTH = true,
			--Solo Shuffle / Battleground Blitz
			SOLO_SHUFFLE = true,
			BLITZ = true,
			--Achievements
			ACHI_SHOW = true,
			--Misc
			DISABLE_EMPTY_DATA = false,
			DISABLE_RAIDS_DUNGEONS = true,
			DISABLE_IN_COMBATENV = false,
			DISABLE_IN_PVPENV = false,

		--arenas&battlegrounds settings

			INST_CURR_RATING_2s = true,
			INST_CURR_RATING_3s = true,
			INST_CURR_RATING_RBG = true,
			--Current Season Stats
			INST_CURR_SEASON_2SW = true,
			INST_CURR_SEASON_3SW = true,
			INST_CURR_SEASON_RBGW = true,
			INST_CURR_SEASON_TITLES = true,
			--Character Experience
			INST_CHAR_EXP_2s = true,
			INST_CHAR_EXP_3s = true,
			INST_CHAR_EXP_RBG = true,
			--Highest Account Rating
			INST_HIGHEST_ACC_2s = true,
			INST_HIGHEST_ACC_3s = true,
			INST_HIGHEST_ACC_RBG = true,
			--Character Stats
			INST_STATS_ITEMLEVEL = true,
			INST_STATS_VERSATILITY = true,
			INST_STATS_COVENANT = true,
			INST_STATS_RENOWN = true,
			INST_STATS_HEALTH = true,
			--Solo Shuffle / Battleground Blitz
			INST_SOLO_SHUFFLE = true,
			INST_BLITZ = true,
			--Achievements
			INST_ACHI_SHOW = true,
		}
	end
	
	if AMPVP_SettingsVar ~= nil and AMPVP_SettingsVar.DISABLE_IN_COMBATENV == nil then
		AMPVP_SettingsVar.DISABLE_IN_COMBATENV = false;
	end
	
	if AMPVP_SettingsVar ~= nil and AMPVP_SettingsVar.DISABLE_IN_PVPENV == nil then
		AMPVP_SettingsVar.DISABLE_IN_PVPENV = false;
	end

	-- Toggles added in 2.0. Anyone upgrading already has a saved settings table,
	-- so default the new keys on or the Solo Shuffle / Blitz sections would never
	-- render for them.
	if AMPVP_SettingsVar ~= nil then
		for _, key in ipairs({ "SOLO_SHUFFLE", "BLITZ", "INST_SOLO_SHUFFLE", "INST_BLITZ" }) do
			if AMPVP_SettingsVar[key] == nil then
				AMPVP_SettingsVar[key] = true
			end
		end
	end
	
end

local frameInitSettings = CreateFrame("frame")
frameInitSettings:RegisterEvent("PLAYER_LOGIN")
frameInitSettings:SetScript("OnEvent", AMPVP_LoginSettingsLoadSave)

local function AMPVP_FailsafeReturn(root, query, returnTable)
	local ids, len = {}, 0
	for id in query:gmatch('[^.]+') do
		len = len + 1
		ids[len]= id
	end

	local node = root
	for i=1,len do
		if type(node) ~= 'table' then return nil end
		node = node[ids[i]]
	end
	return node
end

local function AMPVP_TableofStringsHasEntries(t,s)
  if t == nil then return false end
  local t = t
  for key in s:gmatch('[^.]+') do
    if t[ key ] == nil then
		return false
	end
    t = t[ key ]
  end
  return t
end


function AMPVP_IsBadReadValue(value)
	if value == nil then
		return true
	end

	if type(value) == "string" then
		if value == nil or value == "" then
			return true;
		end
	elseif type(value) == "number" then
		if value == nil or value == 0 then
			return true;
		end
	end

	return false;
end

function AMPVP_GetValue(tableX, entries, isArray)
	if tableX == nil or entries == nil then print(entries .. " are null.") return nil end

	local val = nil

	if isArray then
		local strF = "";
		local ok = nil;
		ok = AMPVP_TableofStringsHasEntries(tableX, entries);

		if ok ~= nil and type(ok) == 'table' then
			for k, v in pairs(ok) do
				if ok[k] ~= nil and v ~= "" then
					strF = strF .. v .. "\n"
				end
			end
		end
		if strF ~= "" then
			return strF
		else
			return nil
		end

	else
		val = AMPVP_FailsafeReturn(tableX, entries)
	end

	if val ~= nil then
		local isBad = AMPVP_IsBadReadValue(val)
		if not isBad then
			return val;
		end
	end

	return nil;
end

function AMPVP_GetSettingValue(setting)
	local db = AMPVP_SettingsVar

	if db == nil then return end

	if db[setting] ~= nil then
		return db[setting]
	end

	return false
end
